// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_secret`

/// Starts an iroh node to share a specific file.
Stream<String> startSend({required String filePath, required String dataDir}) =>
    RustLib.instance.api.crateApiStartSend(
      filePath: filePath,
      dataDir: dataDir,
    );

/// Receives a file using a ticket.
Stream<String> receiveFile({
  required String ticketStr,
  required String dataDir,
  required String downloadDir,
}) => RustLib.instance.api.crateApiReceiveFile(
  ticketStr: ticketStr,
  dataDir: dataDir,
  downloadDir: downloadDir,
);
