import 'package:flutter/material.dart';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:flutter/services.dart'; // For clipboard
import 'package:hole/src/rust/api.dart'; // Generated by FRB
import 'package:hole/src/rust/frb_generated.dart'; // Generated by FRB

void main() async {
  await RustLib.init();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hole',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Hole'),
        bottom: TabBar(
          controller: _tabController,
          tabs: const [
            Tab(icon: Icon(Icons.upload), text: 'Send'),
            Tab(icon: Icon(Icons.download), text: 'Receive'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: const [
          SendPage(),
          ReceivePage(),
        ],
      ),
    );
  }
}

class SendPage extends StatefulWidget {
  const SendPage({super.key});

  @override
  State<SendPage> createState() => _SendPageState();
}

class _SendPageState extends State<SendPage> {
  String? _selectedPath;
  List<String> _logs = [];
  String? _ticket;
  bool _isSharing = false;

  Future<void> _pickAndShare() async {
    if (_isSharing) return;

    // file_picker usually doesn't need pre-requested permissions on Android
    // as it uses intents. Manual check can cause "Mismatch between current collecting".
    
    FilePickerResult? result = await FilePicker.platform.pickFiles();
    if (result != null && result.files.single.path != null) {
      setState(() {
        _selectedPath = result.files.single.path;
        _logs = ["Selected: $_selectedPath"];
        _ticket = null;
        _isSharing = true;
      });

      final appDir = await getApplicationDocumentsDirectory();
      
      try {
        final stream = startSend(
          filePath: _selectedPath!, 
          dataDir: appDir.path
        );
        
        await for (final msg in stream) {
          if (msg.startsWith("TICKET:")) {
            setState(() {
              _ticket = msg.substring(7);
            });
          }
          setState(() {
            _logs.add(msg);
          });
        }
      } catch (e) {
        setState(() {
          _logs.add("Error: $e");
          _isSharing = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        children: [
          ElevatedButton.icon(
            onPressed: _isSharing ? null : _pickAndShare,
            icon: const Icon(Icons.file_open),
            label: const Text('Pick File & Share'),
          ),
          const SizedBox(height: 20),
          if (_ticket != null) ...[
            const Text("Share this Ticket:", style: TextStyle(fontWeight: FontWeight.bold)),
            SelectableText(
              _ticket!,
              style: const TextStyle(fontFamily: 'monospace', backgroundColor: Colors.black12),
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                IconButton(
                  icon: const Icon(Icons.copy),
                  tooltip: 'Copy Ticket',
                  onPressed: () {
                    Clipboard.setData(ClipboardData(text: _ticket!));
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('Ticket copied!')),
                    );
                  },
                ),
                IconButton(
                  icon: const Icon(Icons.qr_code),
                  tooltip: 'Show QR Code',
                  onPressed: () {
                    showDialog(
                      context: context,
                      builder: (context) => AlertDialog(
                        title: const Text('Ticket QR Code'),
                        content: SizedBox(
                          width: 250,
                          height: 250,
                          child: Center(
                            child: QrImageView(
                              data: _ticket!,
                              version: QrVersions.auto,
                              size: 200.0,
                            ),
                          ),
                        ),
                        actions: [
                          TextButton(
                            onPressed: () => Navigator.pop(context),
                            child: const Text('Close'),
                          ),
                        ],
                      ),
                    );
                  },
                ),
              ],
            ),
          ],
          const Divider(),
          Expanded(
            child: ListView.builder(
              itemCount: _logs.length,
              itemBuilder: (ctx, i) => Text(_logs[i], style: const TextStyle(fontSize: 12)),
            ),
          ),
        ],
      ),
    );
  }
}

class ReceivePage extends StatefulWidget {
  const ReceivePage({super.key});

  @override
  State<ReceivePage> createState() => _ReceivePageState();
}

class _ReceivePageState extends State<ReceivePage> {
  final _controller = TextEditingController();
  List<String> _logs = [];
  bool _isDownloading = false;

  Future<void> _startDownload() async {
    final ticket = _controller.text.trim();
    if (ticket.isEmpty || _isDownloading) return;

    setState(() {
      _isDownloading = true;
      _logs = ["Starting download..."];
    });

    try {
      final appDir = await getApplicationDocumentsDirectory();
      // Use app private directory for downloads to avoid needing external storage permissions
      final downloadDir = Directory('${appDir.path}/downloads');
      if (!await downloadDir.exists()) {
        await downloadDir.create(recursive: true);
      }
      
      final stream = receiveFile(
        ticketStr: ticket,
        dataDir: appDir.path,
        downloadDir: downloadDir.path
      );

      await for (final msg in stream) {
        setState(() {
          _logs.add(msg);
        });
      }
    } catch (e) {
      setState(() {
        _logs.add("Error: $e");
      });
    } finally {
      setState(() {
        _isDownloading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        children: [
          Row(
            children: [
              Expanded(
                child: TextField(
                  controller: _controller,
                  decoration: const InputDecoration(
                    labelText: 'Paste Ticket Here',
                    border: OutlineInputBorder(),
                  ),
                ),
              ),
              const SizedBox(width: 8),
              IconButton(
                icon: const Icon(Icons.qr_code_scanner),
                onPressed: _scanQRCode,
                tooltip: 'Scan QR Code',
              ),
            ],
          ),
          const SizedBox(height: 10),
          ElevatedButton(
            onPressed: _isDownloading ? null : _startDownload,
            child: const Text('Download'),
          ),
          const Divider(),
          Expanded(
            child: ListView.builder(
              itemCount: _logs.length,
              itemBuilder: (ctx, i) => Text(_logs[i], style: const TextStyle(fontSize: 12)),
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _scanQRCode() async {
    // Request camera permission
    var status = await Permission.camera.request();
    if (status.isGranted) {
      if (!mounted) return;
      final String? code = await Navigator.push(
        context,
        MaterialPageRoute(builder: (context) => const QRScannerScreen()),
      );

      if (code != null) {
        setState(() {
          _controller.text = code;
        });
      }
    } else {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Camera permission is required to scan QR code')),
      );
    }
  }
}

class QRScannerScreen extends StatelessWidget {
  const QRScannerScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Scan Ticket QR Code')),
      body: MobileScanner(
        onDetect: (capture) {
          final List<Barcode> barcodes = capture.barcodes;
          for (final barcode in barcodes) {
            if (barcode.rawValue != null) {
              Navigator.pop(context, barcode.rawValue);
              break;
            }
          }
        },
      ),
    );
  }
}
