import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:flutter/services.dart'; // For clipboard
import 'package:hole/src/rust/api.dart'; // Generated by FRB
import 'package:hole/src/rust/frb_generated.dart'; // Generated by FRB

void main() async {
  await RustLib.init();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hole',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Hole'),
        bottom: TabBar(
          controller: _tabController,
          tabs: const [
            Tab(icon: Icon(Icons.upload), text: 'Send'),
            Tab(icon: Icon(Icons.download), text: 'Receive'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: const [
          SendPage(),
          ReceivePage(),
        ],
      ),
    );
  }
}

class SendPage extends StatefulWidget {
  const SendPage({super.key});

  @override
  State<SendPage> createState() => _SendPageState();
}

class _SendPageState extends State<SendPage> {
  String? _selectedPath;
  List<String> _logs = [];
  String? _ticket;
  bool _isSharing = false;

  Future<void> _pickAndShare() async {
    if (_isSharing) return;

    // file_picker usually doesn't need pre-requested permissions on Android
    // as it uses intents. Manual check can cause "Mismatch between current collecting".
    
    FilePickerResult? result = await FilePicker.platform.pickFiles();
    if (result != null && result.files.single.path != null) {
      setState(() {
        _selectedPath = result.files.single.path;
        _logs = ["Selected: $_selectedPath"];
        _ticket = null;
        _isSharing = true;
      });

      final appDir = await getApplicationDocumentsDirectory();
      
      try {
        final stream = startSend(
          filePath: _selectedPath!, 
          dataDir: appDir.path
        );
        
        await for (final msg in stream) {
          if (msg.startsWith("TICKET:")) {
            setState(() {
              _ticket = msg.substring(7);
            });
          }
          setState(() {
            _logs.add(msg);
          });
        }
      } catch (e) {
        setState(() {
          _logs.add("Error: $e");
          _isSharing = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        children: [
          ElevatedButton.icon(
            onPressed: _isSharing ? null : _pickAndShare,
            icon: const Icon(Icons.file_open),
            label: const Text('Pick File & Share'),
          ),
          const SizedBox(height: 20),
          if (_ticket != null) ...[
            const Text("Share this Ticket:", style: TextStyle(fontWeight: FontWeight.bold)),
            SelectableText(
              _ticket!,
              style: const TextStyle(fontFamily: 'monospace', backgroundColor: Colors.black12),
            ),
            IconButton(
              icon: const Icon(Icons.copy),
              onPressed: () {
                Clipboard.setData(ClipboardData(text: _ticket!));
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Ticket copied!')),
                );
              },
            ),
          ],
          const Divider(),
          Expanded(
            child: ListView.builder(
              itemCount: _logs.length,
              itemBuilder: (ctx, i) => Text(_logs[i], style: const TextStyle(fontSize: 12)),
            ),
          ),
        ],
      ),
    );
  }
}

class ReceivePage extends StatefulWidget {
  const ReceivePage({super.key});

  @override
  State<ReceivePage> createState() => _ReceivePageState();
}

class _ReceivePageState extends State<ReceivePage> {
  final _controller = TextEditingController();
  List<String> _logs = [];
  bool _isDownloading = false;

  Future<void> _startDownload() async {
    final ticket = _controller.text.trim();
    if (ticket.isEmpty || _isDownloading) return;

    // Proper permission check for Android
    if (await _requestPermissions()) {
      setState(() {
        _isDownloading = true;
        _logs = ["Starting download..."];
      });

      final appDir = await getApplicationDocumentsDirectory();
      final downloadDir = await getDownloadsDirectory() ?? await getApplicationDocumentsDirectory();
      
      try {
        final stream = receiveFile(
          ticketStr: ticket,
          dataDir: appDir.path,
          downloadDir: downloadDir.path
        );

        await for (final msg in stream) {
          setState(() {
            _logs.add(msg);
          });
        }
      } catch (e) {
        setState(() {
          _logs.add("Error: $e");
        });
      } finally {
        setState(() {
          _isDownloading = false;
        });
      }
    } else {
      setState(() {
        _logs.add("Error: Storage permission denied");
      });
    }
  }

  Future<bool> _requestPermissions() async {
    // Android 13+ (API 33+)
    if (await Permission.manageExternalStorage.isGranted) return true;
    
    Map<Permission, PermissionStatus> statuses = await [
      Permission.storage,
      // For Android 11+ to save to Downloads
      Permission.manageExternalStorage, 
    ].request();
    
    return statuses[Permission.storage]!.isGranted || 
           statuses[Permission.manageExternalStorage]!.isGranted;
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        children: [
          TextField(
            controller: _controller,
            decoration: const InputDecoration(
              labelText: 'Paste Ticket Here',
              border: OutlineInputBorder(),
            ),
          ),
          const SizedBox(height: 10),
          ElevatedButton(
            onPressed: _isDownloading ? null : _startDownload,
            child: const Text('Download'),
          ),
          const Divider(),
          Expanded(
            child: ListView.builder(
              itemCount: _logs.length,
              itemBuilder: (ctx, i) => Text(_logs[i], style: const TextStyle(fontSize: 12)),
            ),
          ),
        ],
      ),
    );
  }
}
